# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField()),
                ('student_class', models.CharField(max_length=5)),
                ('branch', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('batch', models.CharField(max_length=9)),
            ],
        ),
    ]
